"""auto-vote

Revision ID: dea070db6cbf
Revises: 6386b986b217
Create Date: 2024-01-25 17:25:24.890415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea070db6cbf'
down_revision: Union[str, None] = '6386b986b217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes', sa.Column('users_id', sa.Integer(), nullable=False),
                    sa.Column('posts_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('users_id', 'posts_id'))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    pass
    # ### end Alembic commands ###
